name: Masschelein

channels:
  - conda-forge
      
dependencies:
  - python=3.10
  - numpy=1.23
  - scipy
  - scikit-image
  - pandas
  - opencv
  - joblib
  - matplotlib-base=3.6
  - pip
  - pip:
    - pip install napari[all] magicgui
    - pylibCZIrw
    - aicspylibczi>=3.1.1
    - fsspec>=2022.8.0