name: Masschelein

channels:
  - conda-forge

dependencies:
  # conda_core
  - python=3.10
  - numpy=1.24*
  - numba
  - scipy
  - pandas
  - scikit-image
  - opencv
  - scikit-learn
  - joblib
  - matplotlib-base
  - pip
  # conda_spec
  - napari
  - pyqt
  - spyder
  - pip:
    # pip_core
    - bd-tools==0.2.2
    # pip_spec
    - pylibczirw
    - aicspylibczi >=3.1.1
    - fsspec >=2022.8.0