name: Masschelein

channels:
  - conda-forge

dependencies:
  # conda_core
  - python=3.10
  - numpy=1.24*
  - scipy
  - pandas
  - scikit-image
  - opencv
  - scikit-learn
  - joblib
  - matplotlib-base
  - pip
  # conda_spec
  - napari
  - magicgui
  - pyqt
  - spyder
  # conda_tf_nogpu
  - pip:
    # pip_core
    # pip_spec
    - pylibczirw
    - aicspylibczi>=3.1.1
    - fsspec>=2022.8.0
    # pip_tf_nogpu
    - albumentations
    - segmentation-models
    - tensorflow==2.10